### ISSUE TITLE
Whitespace

### ISSUE THREAD

**Issue by tj** [Bowery/prompt#11]
Thanks for the pkg! 

Stupid minor thing but would you be cool with:

```
Auto renew? (y/n) |
```

instead of:

```
Auto renew?(y/n)|
```

where `|` is the cursor, feels a little cramped.

**Comment by larzconwell** [comment]
Yeah I'm down with that, it looks a lot nicer.

**Comment by sjkaliski** [comment]
+1, should it be configurable? e.g. `prompt.CursorPrefix`?

**Comment by larzconwell** [comment]
I'm not sure if it's worth it for just adding a space before the cursor, I feel like everyone would just use the default unless they wanted to be super pedantic. I think just changing up the spacing in `term.go` would be enough.
