### ISSUE TITLE
Fails on 32-bit systems

### ISSUE THREAD

**Issue by yurivict** [Bowery/prompt#14]
It fails for the "govendor" project, see the details here: https://github.com/kardianos/govendor/issues/386#issuecomment-364259597

**Comment by NHOrus** [comment]
That uses old version of this package.

**Comment by NHOrus** [comment]
See https://github.com/Bowery/prompt/commit/eb8f7a6a197ce971ed0e9d4a739c628381d5f124

**Comment by larzconwell** [comment]
Thank you @NHOrus, this has indeed been fixed so I'm going to close unless @yurivict you happen to be running on the latest master
